version: '3'

rpc:
    listen: tcp://127.0.0.1:6001

server:
    command: "php worker.php"
    relay: pipes

http:
    address: "0.0.0.0:8080"

pool:
    num_workers: 4
    max_jobs: 100
    allocate: 4

logs:
    level: debug

headers:
    server: "RoadRunner"
